services:
  - type: web
    name: recaptcha
    env: python
    buildCommand: |
      ./render-build.sh
      pip install -r requirements.txt
      playwright install
    startCommand: gunicorn app:app
